### ISSUE TITLE
#9 Meetup Front-End CE - Call For Papers

### ISSUE THREAD

**Issue by jeanlivino** [frontend-ce/meetups#10]
Fala galera, beleza?

Essa é a Issue destinada para a realização do call 4 papers para o nosso **último Meetup do ano que acontecerá no dia 14 de dezembro.**

Algumas observações:
1: Somente **duas serão escolhidas,** as que tiverem maior quantidade de reações nesta issue.
2: Palestrante precisa estar disponível das 14 as 18h
3: Votações serão válidas **até dia 27/11** para **divulgação no dia 28/11**

O modelo para submissão de talk é o seguinte:
[Nome do Palestrante] - [Tema da Palestra/Talk]
[Resumo da Palestra/Talk]

**Comment by hileomsi** [comment]
Hiléo Andersson - GraphQL: Um panorama sobre seu funcionamento.

Com a idéia de melhorar a perfomance, documentação, organização e trazer um novo conceito a consulta de dados de API, a linguagem de consulta de dados GraphQL apareceu. O objetivo da palestra é conversar sobre sua criação, o que trouxe de novo, vantagens e desvantagens, explicar seus conceitos, e mostrar exemplos no lado do front-end e back-end.

**Comment by ghost** [comment]
Edmo Lima - O mundo real e os microfrontends.

Bom desenvolvimento de front-end é difícil. Escalar o desenvolvimento de front-end para que muitas equipes possam trabalhar simultaneamente em um produto grande e complexo é ainda mais difícil. Nessa talk falaremos da tendência recente de dividir monólitos de front-end em muitas partes menores e mais gerenciáveis, e como essa arquitetura pode aumentar a eficácia e a eficiência das equipes que trabalham no código de front-end.

É hora de expor toda a experiência adquirida após os últimos 2 anos e meio trabalhando em projetos usando essa arquitetura. O objetivo é mostrar os desafios, cenários de uso, técnicas utilizadas em algumas experiências, a vida por trás do hype e erros e acertos da implementação.

**Comment by adaltojunior86** [comment]
Adalto Junior - Immer.js mais uma alternativa para trabalhar com imutabilidade.
O objetivo da palestra é fazer um overview desse framework para trabalhar com estrutura de dados imutáveis.

**Comment by joaowillamy** [comment]
### **Guia Javascript para 2020** 

Com muito amor e ódio envolvido, vamos discutir sobre algumas das tecnologias mais populares dos últimos tempos: Angular, React, Vue, Node.js, Express.js e Redux serão algumas das tecnologias em pauta. 

Curva de aprendizado é importante? Lib ou framework? Liberdade de escolha ou decisões previamente tomadas? Qual é a melhor para trabalho em equipe? Essas são algumas de perguntas importantes que podemos debater juntos. 

**AVISO IMPORTANTE:**
Essa talk não tem o objetivo de ser dona da verdade, mas sim fomentar questionamentos e analisar informações ou simplesmente causar a treta.

**Comment by amadeirado** [comment]
Anderson Madeira - React Hooks - Um novo React, apenas hype ou uma armadilha?

Com a adição de Hooks não tão recente a React, algumas polêmicas surgiram, muito hype e alguns até dizem que é um novo e muito melhor React. Mas afinal o que são hooks? É só pra não usar classes? Como funcionam? O que eu preciso saber antes de começar a usar Hooks em minha aplicação React? O que são closures? Hooks substituem Redux? Quais são as motivações para o uso de Hooks? Como reutilizar comportamento com Hooks?

Aplicações práticas:
- Class Components vs Funcional Components: Gerenciando estado de um componente
- Como usar Portals com Hooks?
- Como usar Context API com Hooks? Isso substitui Redux?

A nossa conversa terá como objetivo entendermos em linhas gerais como Hooks funcionam, vermos aplicações práticas e os perigos ou armadilhas que precisam ser evitados.

**Comment by AbraaoAlves** [comment]
Typescript em React-Redux apps

Como se beneficiar de tipos em um mundo onde os dados tem um papel central no fluxo da aplicação? Não tenha mais dor de cabeça com tipos, ANYmore ...

Nessa palestra irei apresentar um conceito/filosofia de como manter seu codigo 100% tipado sem a necessidade de reescrever* seus tipos em cada modulo de codigo, facilitando o porte do seu app de JS para TS, ou apenas para manter seus contratos de dados intactos, desde seus reducers , passando pelos selectors, até seus components!

(SpoilerAlert*): Porque escrever uma type/interface se o state da sua aplicação guarda todas as informações importantes para um contrato de dados?

**Comment by igoventura** [comment]
Igo Ventura - **WebAssembly na prática com Blazor**

> O WA vem sendo uma aposta já faz um tempo mas ainda não temos casos de uso dessa tecnologia. 

Aqui apresento como utilizar o Blazor, uma tecnologia feita pela Microsoft para o desenvolvimento de web clients com C# e WA. Durante a talk mostrarei na prática como criar uma nova aplicação usando esta tecnologia, além de mostrar seu benefícios e como fazer interop com JS.

**Comment by webjoaoneto** [comment]
João Neto - **Fim do QueroWorkar. E agora?** (Treta💀)
`Para onde vão nossas vagas agora?`
Muito se tem falado desde a notícia do fim do QUeroWorkar. Gente querendo forkar o projeto, reescreve-lo em Wordpress, fazer outro do zero, comprar um projeto pronto ou só mesmo acompanhar a treta.

Então, diante desse cenário onde ficaremos praticamente orfãos de um portal de jobs local voltado pra noss área, apresentarei no meetup um MVP que eu criei e disponibilizo para a comunidade para que possamos juntos ♡ melhora-lo a cada dia e ajudar a empresas e profissionais a encontrarem um novo Job. 

Projeto 100% OpenSource baseado no Strapi + Nuxt.js, onde a propria comunidade vai guiar a evolução do projeto. Afinal, tudo que precisamos é um local onde estejam todas as vagas e nada mais.

**Comment by cicerohen** [comment]
Cícero Viana - **JavaScript Tooling**
Keep calm e vamos aprender configurar e entender os porquês das principais ferramentas usadas durante o build de uma aplicação JavaScript, como ESLint, Prettier, Babel e outras.

**Comment by cicerohen** [comment]
Cícero Viana - **Como aprender algo novo**
Diante da infinidade de fontes de informação, como se manter motivado e aprender o essencial para a prática?

Nessa talk iremos conversar sobre as abordagens durante o processo de aprendizado de novos conceitos, ferramentas, etc.

**Comment by cicerohen** [comment]
@AbraaoAlves confirma tua talk no frontendce?
