### ISSUE TITLE
#10 Meetup Front-End CE - CallForPaper

### ISSUE THREAD

**Issue by jeanlivino** [frontend-ce/meetups#11]
Fala galera, beleza?

Essa é a Issue destinada para a realização do call 4 papers para o nosso primeiro Meetup de 2020 que acontecerá no dia **01 de fevereiro.**

Algumas observações:
1: Somente 3 serão escolhidas, as que tiverem maior quantidade de reações nesta issue.
2: Palestrante precisa estar disponível das 14 as 18h
3: Votações serão válidas até dia 12/01 para divulgação no dia 13/01

O modelo para submissão de talk é o seguinte:
[Nome do Palestrante] - [Tema da Palestra/Talk]
[Resumo da Palestra/Talk]

**Comment by gleysonlf** [comment]
**Gleyson Lira - Sharepoint? Nunca ouvi falar!**
Nesta palestra, gostaria de fazer uma apresentação do Microsoft Sharepoint, o mercado de trabalho relacionado e como eu fui dentro dele.

**Comment by helrabelo** [comment]
Hel Rabelo - Is Gatsby really great?
Nessa palestra, apresentarei o framework Gatsby e uma aplicação do mesmo no desenvolvimento de um website de portfólio pessoal.

**Comment by helrabelo** [comment]
**Hel Rabelo - Is Gatsby really great?**
Nessa palestra, apresentarei o framework Gatsby e uma aplicação do mesmo no desenvolvimento de um website de portfólio pessoal.

**Comment by carlosxjm** [comment]
**Carlos José - Javascript Event Loop** 
"Como o Javascript, sendo monothread, executa tarefas assíncronas?"
Esse é o tipo de dúvida que temos quando não entendemos como o javascript é executado.
E a ideia dessa talk é esclarecer isso, explicar um pouco do funcionamento do javascript no navegador.

**Comment by cicerohen** [comment]
TDD/BDD além dos frameworks JavaScript. 
Nessa talk irei falar dos conceitos por trás dos testes e de algumas ferramentas que foram/são usadas para testar código JavaScript.

**Comment by cicerohen** [comment]
História dos module loaders no JavaScript.
Nessa talk irei falar da evolução na modularização do código JavaScript

**Comment by cicerohen** [comment]
Não tenha medo do DevTools.
Nesta talk irei mostrar como usar o essencial do DevTools(Chrome/Firefox) para facilitar sua vida durante o desenvolvimento.

**Comment by amadeirado** [comment]
**Anderson Madeira - Princípios de Programação Funcional em JavaScript**
Vamos conversar um pouco sobre alguns princípios de programação funcional que podem ser usados em JavaScript de maneira agnóstica à frameworks, como imutabilidade e funções*. Veremos como desenvolver assim pode melhorar nossas aplicações ao torná-las livres de efeitos colaterais indesejados, fazendo assim código mais previsível, fácil de se manter e testar.

EDIT: 
*Correção de erro de digitação: funções puras.

**Comment by joaowillamy** [comment]
**Exemplos práticos de SCSS Avançado** 
_João Willamy_ 

 A ideia é de aumentar o nível de conhecimento em SCSS e sair com alguns insight legais para aplicar o conhecimento. **Os exemplos práticos ilustrarão a explicação sobre os tópicos abordados**: function, mixin,  criando loops com (each, for) tipos complexos.

**Comment by geeksilva97** [comment]
## Edigleysson Silva - Do zero ao app com Firebase

Vamos ter um overview sobre o Firebase de uma forma prática. A ideia é te mostrar como você pode criar um app de forma rápida e simples porém com um grande potencial. Que tal sair dessa talk, chegar em casa e criar sua aplicação de chat com autenticação e realtime em apenas 20 minutos?

**Comment by amadeirado** [comment]
**Anderson Madeira - Bulindo no DOM com JavaScript**

_Você sabe o que é o DOM?_

Nessa conversa vamos entender o que é; vamos falar sobre eventos, estilos e outras coisas que podem ser encontradas sobre a página ao inspecionar o DOM. Vamos falar também de maneira introdutória sobre _**shadow dom**_ e quais os benefícios que ele traz pra _**SPAs**_ na web moderna. Como exercício prático, vamos brincar com o DOM e fazer um pequeno robô ou _**web crawler**_ em JS puro pra perturbar aquela pessoa chata que não te responde no ZAP ou Telegram. _(Sdds do MSN Messenger né? hehe)_

Edição1:
Melhor formatação
