### ISSUE TITLE
#3 Meetup Online | Women Edition

### ISSUE THREAD

**Issue by felipepatricio** [frontend-ce/meetups#13]
Fala galera, beleza?

Essa é a Issue destinada para a realização do call 4 papers para o nosso terceiro meetup online que acontecerá no **dia 21/08,** o primeiro em que teremos somente **palestrantes mulheres.**

Algumas observações:

1. Somente 3 serão escolhidas, as que tiverem maior quantidade de reações nesta issue.
2. Palestrante precisa estar disponível das **19:00** às **21:00**
3. Votações serão válidas até dia **14/08** para divulgação no dia **15/08**

O modelo para submissão de talk é o seguinte:
**[Nome da Palestrante]** - **[Tema da Palestra/Talk]**
**[Resumo da Palestra/Talk]**

**Comment by hedenica** [comment]
Olá, gostaria de participar! 🙋🏻‍♀️
**Hedênica Morais** - Dicas para se **destacar** no LinkedIn

Pequenos ajustes em nossa forma de utilizar uma rede social como o LinkedIn, 
pode abrir portas para quem está procurando aquela vaga tão sonhada.
Dicas e exemplos do que eu fiz, que trouxeram resultados para iniciar minha carreira como Dev. Front-end

**Comment by RaissaMariaB** [comment]
Olá! Quero muito participar!

tema de acessibilidade na web
Raissa Barata - Web para todos

Resumo: No mundo do desenvolvimento, sabemos o quanto é importante que todos tenham acesso ao conteúdo que é passado no seu site. Mas será que fazemos por onde esse conteúdo ser acessível a todos?  nessa talk ofereço uma introdução sobre o que é e porque acessibilidade na web é importante. Por onde podemos começar a identificar as más e boas práticas, deixando nosso  nosso código mais inclusivo.

**Comment by amandarsl** [comment]
**Amanda Rebeca** - Por que e como estou migrando para área de TI?

**Resumo:** Falta de qualidade de vida, falta de oportunidade, desvalorização, descaso, necessidade de se re-inventar e de acompanhar o novo, são alguns dos fatores que servem ou devem servir como motivação para mudar de vida. Tomar a iniciativa, encontrar uma rede de apoio e investir, sobretudo, tempo é necessário para realizar toda e qualquer mudança de rotina. Não é fácil e nunca vai ser, não existe receita pronta ou formula mágica, é preciso vontade e determinação. Nessa apresentação eu conto o que me motivou e como estou iniciando minha jornada na área de TI como uma aspirante a **Desenvolvedora Front-end**.

**Comment by franciane-lark** [comment]
Parabéns. Incrível. Amei.
