### ISSUE TITLE
#4 Meetup Online | Call for Papers

### ISSUE THREAD

**Issue by WLSF** [frontend-ce/meetups#15]
Fala galera, beleza?

Esta é a Issue destinada para a realização do **call4papers** para o nosso 4º Meetup Online que acontecerá no dia 28 de janeiro.

Algumas observações:
1: Somente 3 serão escolhidas, as que tiverem maior quantidade de likes 👍🏻 nesta issue.
2: Palestrante precisa estar disponível das 18h30 as 21h30
3: Votações serão válidas até dia 20/01 para divulgação no dia 21/01

O modelo para submissão de talk é o seguinte:
[Nome Palestrante] - [Tema da Palestra/Talk]
[Resumo da Palestra/Talk]

**Comment by julianosbento** [comment]
[Custom Hooks] - [Fisgando a lógica sem comprometer sua view]
[Talkzinha sobre como criar componentes desacoplados da lógica, possibilitando a construção de componentes "burros" de forma fácil, e melhorando a mudularização e reaproveitamento de código e componentes, utilizando React / React Native]

**Comment by joaowillamy** [comment]
[joaowillamy] - [clean code vs XGH, um papo sobre Qualidade e produtividade]

Imagine trabalhar em um lugar onde o código simplesmente melhorou com o tempo? Para que isso aconteça devemos tratar a refatoração como parte do conceito de pronto. Dessa forma, podemos abordar algumas estratégias para incorporar no nosso dia a dia.

**Comment by amadeirado** [comment]
[andersonmadeira] - [10 lições que aprendi com acessibilidade]
Nessa conversa vamos entender o que é acessibilidade na web de maneira descomplicada, porque é importante, instruções gerais de como implementar e por fim vamos tirar 10 lições dessa conversa que farão nossas aplicações mais acessíveis.

**Comment by joeljuca** [comment]
[Joel Jucá](https://twitter.com/holyshtjoe) - Minimalismo JS

JavaScript é uma tecnologia complexa. Por motivos históricos, é comum ver inúmeros projetos afundados em quilos e mais quilos de dependências - tanto de desenvolvimento quanto de produção! Os memes sobre pastas node_modules com centenas de MBs não me deixam mentir. Nessa talk eu vou falar de técnicas simples para diminuir a complexidade de projetos JS ao facilitar nossas próprias vidas como desenvovledores web.
