### ISSUE TITLE
#11 Meetup PRESENCIAL Front-End CE - CallForPaper

### ISSUE THREAD

**Issue by jeanlivino** [frontend-ce/meetups#17]
Fala galera, beleza?
**SIM, isso mesmo meetup PRESENCIAL!**

Essa é a Issue destinada para a realização do call 4 papers para o nosso primeiro Meetup de 2022 que acontecerá no dia 14 de maio na Digital College - Aldeota.

Algumas observações:
1: Somente 3 serão escolhidas, as que tiverem maior quantidade de reações nesta issue.
2: Palestrante precisa estar disponível das 14 as 18h
3: Votações serão válidas até dia 25/04 para divulgação no dia 26/04

**O modelo para submissão de talk é o seguinte:**
[Nome do Palestrante] - [Tema da Palestra/Talk]
[Resumo da Palestra/Talk]

**Comment by joaowillamy** [comment]
João Willamy - A Jornada de Mary! Como entender de gestão ajuda a implantar novas tecnologias? 

Antes de implantar qualquer coisa, vale entender qual é o contexto geral. Pergunte-se:
Estou capacitado para implementar essa tech? O time entrega bem? Tem algum problema com o time? Está comprometido com minha evolução? O projeto é um MVP? Scale up? Unicórnio? É do interesse geral da empresa? O momento do mercado ajuda?

Além disso, vale entender também qual é o seu papel nessa mudança, qual seu nível de conhecimento e qual o tamanho do impacto que você terá nas suas entregas.

Sem falar de aprofundar na tecnologia em questão, e ver se realmente faz sentido aplicar no seu projeto!

Para exemplificar tudo isso, vou mostrar os momentos da carreira de Mary, personagem fictício que deseja implementar micro frontend, e entender sua evolução ao longo dessa jornada, melhorando suas soft e hard skills, saindo do júnior à CTO.

OBS: O intuito dessa palestra é meramente questionar, e não solucionar seus problemas.
OBS2: A historia de Mary é somente pra ilustrar exemplos, não é pra te ensinar a se tornar CTO
OBS3:  Micro Frontend é só um exemplo para a historia de mary.

**Comment by AbraaoAlves** [comment]
### Abraão Alves - Errar não é uma escolha, é uma certeza

Aprenda de vez como gerenciar seus erros no FrontEnd de forma profissional

Resumo:

Se você não está falhando XX% do tempo, algo de errado não está muito certo. Abrace a inevitabilidade dos erros e aprenda como molhorar nossos webapps com eles!

Nessa talk irei falar da importancia e de como implementar o tratamento, rastreamento e monitaramento de erros em nossos apps. Usarei o Sentry, como exemplo de Error Tracking Software, mas os conceitos passados serão uteis para qualquer outro scenário de monitoramento!

**Comment by joeljuca** [comment]
**Joel Jucá - Intro ao asdf**

Esta talk técnica introduz o público ao asdf, uma ferramenta CLI de gestão de versões de runtimes que resolve um problema muito comum no mundo do desenvolvimento de software: gerenciamento de versões de múltiplas runtimes.

O público alvo são desenvolvedores de todos os níveis e/ou profissionais de tecnologia que façam uso de CLI pra realização de tarefas técnicas.
