### ISSUE TITLE
#3 Meetup Frontend CE - Call 4 Papers - 19 de Janeiro

### ISSUE THREAD

**Issue by victornery** [frontend-ce/meetups#3]
Fala galera, beleza?

Essa é a Issue destinada para a realização do call 4 papers para o nosso Meetup do dia **19 de Janeiro**.

A partir de agora, a nossa rodada de Meetups vai acontecer lá no **FB Ideias**, nova empresa parceira da nossa comunidade. Lembrando que nosso meetup vai acontecer no dia 19 de Janeiro.

O modelo para submissão de talk é o seguinte:

`[Nome do Palestrante] - [Tema da Palestra/Talk]`
`[Resumo da Palestra/Talk]`

Até dia **8 de Janeiro**, vamos escolher os palestrantes para nosso evento.

[Link do Evento](http://bit.ly/3meetupfrontce)

Chega junto, dev. 😜👊🏼

**Comment by BradHick** [comment]
Bradley Hick - Formik: React forms without pain
Uma pequena apresentação sobre essa excelente lib para construir formulários no React sem lágrimas

**Comment by cicerohen** [comment]
Cícero Viana - Máquina de estados no desenvolvimento de aplicações modernas
Talk(teoria e prática) sobre como usar React/Redux/Saga com conceitos de máquinas de estados para a produção de aplicações modernas.

**Comment by gleysonlf** [comment]
Gleyson Lira - O Universo da Programação

Um diálogo sobre a carreira de desenvolver e as perspectivas do mercado ver trabalho com o avanço da Tecnologia.

**Comment by manoel-freitas** [comment]
Manoel Freitas - fui programar na maior cidade do Brasil (SP) valeu a pena?

Uma conversa bem aberta sobre oportunidades fora do estado. Sobre morar em outro lugar. E como é trabalhar numa multinacional de consultoria(ACCENTURE)
