### ISSUE TITLE
#4 Meetup Frontend CE - Call 4 Papers - Março

### ISSUE THREAD

**Issue by jeanlivino** [frontend-ce/meetups#6]
Fala galera, beleza?

Essa é a Issue destinada para a realização do call 4 papers para o nosso Meetup do mês de março, ainda não fechamos a data, mas será na segunda quinzena de março em um sábado.

O modelo para submissão de talk é o seguinte:

`[Nome do Palestrante] - [Tema da Palestra/Talk]`
`[Resumo da Palestra/Talk]`

**Comment by cicerohen** [comment]
Cícero Viana - Iniciando com Webpack(teoria e prática)
Iremos discutir o uso do Webpack, suas diferenças em relação a outras tools e fazer as configurações básicas para buildar uma aplicação JS.

**Comment by jp-cordeiro** [comment]
João Paulo Cordeiro - Nunca nem Vue? Uma abordagem descomplicada do simples

Vamos abordar Vue.js de uma forma simples e descomplicada, veremos um pouco da história do criador e como o Vue está em grande ascensão.
Serão abordados os conceitos básicos iniciais para poder desenvolver suas primeiras telas em Vue.js.

**Comment by BradHick** [comment]
Bradley Hick - Rematch: Redesigning Redux
Vamos fazer uma introdução nesse framework que mostra uma abordagem do Redux e as melhorias trazidas por ele.

**Comment by IanRamosC** [comment]
Ian Ramos - Entendendo React Native Animations
Faremos uma breve introdução às animações no mundo do React Native e analisaremos como torná-las mais performáticas e menos complicadas.

**Comment by patriciob00** [comment]
Patricio Bruno - React Hooks, que diabo é isso ?
Uma breve introdução sobre, o que é, porque nasceu e como usar os Hooks do react.
