### ISSUE TITLE
#5 Meetup Frontend CE - Call 4 Papers - 01 de Junho

### ISSUE THREAD

**Issue by jeanlivino** [frontend-ce/meetups#8]
Fala galera, beleza?

Essa é a Issue destinada para a realização do call 4 papers para o nosso Meetup do mês de junho, que acontecerá no dia 1.

O modelo para submissão de talk é o seguinte:

[Nome do Palestrante] - [Tema da Palestra/Talk]
[Resumo da Palestra/Talk]

**Comment by adaltojunior86** [comment]
Adalto Junior - React hooks!!!!!
Vamos destrinchar um pouco sobre essa nova feature do react e mostrar se é preciso usá-la, faz sentido mesmo?

**Comment by BradHick** [comment]
Brad Hick - Styled Components: styling your apps without stress.
Vamos dar uma breve introdução de como usar essa maravilhosa ferramenta.

**Comment by cicerohen** [comment]
Cícero Viana - Expressões Regulares(Teoria e prática)
Iremos brincar um pouco com regex usando exemplos do mundo real. :D

**Comment by webjoaoneto** [comment]
Joao Neto - ParcelJS 
Aprendendo sobre parcel, dicas, como usar e por que ele ajuda tanto no desenvolvimento.
