### ISSUE TITLE
#6 Meetup Front-End CE - Call For Papers - 06 de julho

### ISSUE THREAD

**Issue by jeanlivino** [frontend-ce/meetups#9]
Fala galera, beleza?

Essa é a Issue destinada para a realização do call 4 papers para o nosso Meetup do mês de julho, que acontecerá no dia 6.

**Algumas observações:**
1: **_Somente duas serão escolhidas_**, as que tiverem **_maior quantidade de reações_** nesta issue.
2: Palestrante precisa **_estar disponível das 14 as 19h_**
3: Votações serão válidas **_até dia 15/06_** para divulgação no dia 17/06

O modelo para submissão de talk é o seguinte:
[Nome do Palestrante] - [Tema da Palestra/Talk]
[Resumo da Palestra/Talk]

**Comment by jeanlivino** [comment]
Jean Livino - Estilizando aplicações sem frameworks absurdos (CSS na Prática)

Uma talk sobre como estilizar aplicações sem depender tanto de frameworks pesados. Vou mostrar como uso css no meu dia a dia, pensando na experiência do usuário. Deixarei um espaço aberto para dúvidas práticas de css.

**Comment by hileomsi** [comment]
Hiléo Andersson - React spring: Animações com a facilidade dos hooks

Desenvolvendo animações em react de forma elegante, com exemplos e casos de uso, além de trazer inspirações sobre o assunto.
